on:
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: meta-introspector/checkout@v3.3.0
      - run: yarn install --frozen-lockfile
      - run: yarn test
